name: Test GitHub env vars

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Run code"
        run: |
          echo "Run ID: $GITHUB_RUN_ID" 
          echo "Run Number: $GITHUB_RUN_ID" 
          echo "HTML: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
